### ISSUE TITLE
si son muchos usuarios no se pueden ver los inferiores

### ISSUE THREAD

**Issue by juanpabloaj** [juanpabloaj/programadores-chile-github#8]
cc @undersen 

![ss](http://cl.ly/c682/localhost_3000_y_1__pablo_mba__tmux_-2__tmux__y_pleno_empleo.png)

**Comment by juanpabloaj** [comment]
con estas lineas se puede replicar el problema

```
    //$scope.users = $firebaseArray(refUsers);
    var arr = [];
    for (var i=0; i < 1000; i ++) {
      arr.push({username:'user' + i});
    }
    $scope.users = arr;
```

**Comment by juanpabloaj** [comment]
lo mismo en resolución movil, solo te deja ver los que caben en el alto de la pantalla

**Comment by undersen** [comment]
okeeey, dejame meterle maaano y apenas lo tengo te respondo por aqui :smile:
